Add gfx1151 target
ROCmSoftwarePlatform/hipFFT pull request #105
Opened 2024-09-13 15:55 UTC by amd-garydeng

Summary of proposed changes:
Cherry picking gfx1151 enablement into 6.2

2024-09-22 11:57 UTC, af-ayala approved these changes

2024-09-24 19:54 UTC, eng-flavio-teixeira requested changes
Looks like this PR has some issues and is blocking the staging pipeline: https://ontrack-internal.amd.com/browse/SWDEV-486911.

Please add commit https://github.com/ROCm/hipFFT-internal/commit/41c0be48bd0e239dfdb46d9d982937544c34689e to your PR. It should resolve the compiler errors observed in SWDEV-486911.

2024-09-24 20:09 UTC, eng-flavio-teixeira approved these changes

2024-10-02 16:28 UTC, evetsso approved these changes

2024-10-02 16:29 UTC, merged